######################## default configuration ####################
baseURL = "/"
relativeURLs = true
uglyURLs = true
title = "Andrea Stella's website"
theme = "port"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "My skills"
URL = "#skills"
weight = 3

[[menu.main]]
name = "Contacts"
URL = "#contacts"
weight = 4

#################### default parameters ################################
[params]
logo_light = "images/mylogo.svg"
logo_dark = "images/mylogo_dark.svg"
copyright = "Andrea Stella | "
# Meta data
description = "Personal Portfolio"
author = "Andrea Stella"
favicon = "images/logo.png"
# google_analytics = "G-ABCDEFG123"


# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/endriu00"

[[params.social]]
icon = "fab fa-gitlab"
link = "https://gitlab.com/endriu00"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/andrea-stella-0753151a2/"

[[params.social]]
icon = "fab fa-quora"
link = "https://www.quora.com/profile/Andrea-Stella-30"

[[params.social]]
icon = "fab fa-telegram"
link = "https://t.me/endriustar"

contentDir = "content/english"
weight = 1
home = "Home"